issues:
  exclude-use-default: false
  exclude:
    # Captured by errcheck.
    - '^(G104|G204|G307):'
    # Very commonly not checked.
    - 'Error return value of .(.*Close|os\.Remove(All)?|.*Print(f|ln|)|os\.(Un)?Setenv). is not checked'
    # Ignore unparam for required Kong method signature
    - '\.AfterApply - result 0 \(error\) is always nil'
    - '\.Run - result 0 \(error\) is always nil'
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
      text: 'G304'

linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - goconst
    - goerr113
    - golint
    - gomnd
    - interfacer
    - lll
    - maligned
    - nlreturn
    - paralleltest
    - scopelint
    - testpackage
    - varnamelen
    - wsl
